# CPU
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_MIN_PERF_ON_AC=0
CPU_MAX_PERF_ON_AC=100
CPU_BOOST_ON_AC=1
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
CPU_MIN_PERF_ON_BAT=0
CPU_MAX_PERF_ON_BAT=100
CPU_BOOST_ON_BAT=1

# PCIe/runtime PM
PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersave
RUNTIME_PM_ON_AC=auto
RUNTIME_PM_ON_BAT=auto

# USB/audio/Wi-Fi
USB_AUTOSUSPEND=1
USB_EXCLUDE_AUDIO=1
USB_EXCLUDE_BTUSB=1
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on
