[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "application/*", use = "edit" },
	{ url = "*", use = "edit" },
]

