wallpaper {
    monitor = DP-1
    path = ~/Pictures/catto.jpg
    fit_mode = cover
}

# Fallback wallpaper for any undefined monitors
wallpaper {
    monitor = 
    path = ~/Pictures/catto.jpg
    fit_mode = fill
}
