foreground            #ffe8f3
background            #261b29
selection_foreground  #261b29
selection_background #ffafd0
cursor                #ffafd0
cursor_text_color     #261b29
url_color             #f5a6c8
active_border_color   #ffafd0
inactive_border_color #543553
bell_border_color     #ff759f
active_tab_foreground   #261b29
active_tab_background   #ffafd0
inactive_tab_foreground #d8b4c7
inactive_tab_background #38243b
tab_bar_background      #261b29
color0  #38243b
color1  #c94f78
color2  #8bc9b9
color3  #e8a6bd
color4  #9b7fc1
color5  #d98bb4
color6  #8fd6c8
color7  #d8b4c7
color8  #9f788f
color9  #ff759f
color10 #b8f2e6
color11 #ffd1e3
color12 #f5a6c8
color13 #e7b7ff
color14 #f3a8c8
color15 #ffe8f3
